### ISSUE TITLE
Decouple cloned models from the placeholder parts

### ISSUE THREAD

**Issue by vocksel** [vocksel/prefabs#9]
When prefabs are shown, each one is cloned inside of the placeholder part that represents the prefab.

This is a bad practice for a number of reasons. The biggest problem is Roblox's default grabber tools in Studio can overlook the part and move only the model inside. This ends up repositioning the model, but the placeholder is still in its last position. When you toggle your prefabs, the one you moved ends up at its previous position unexpectedly.

Overall it's a hacky implementation and we can do better. The new proposed implementation will involve moving the placeholders out of the workspace, and using ObjectValues to map a prefab to its associated placeholder.

A problem with this implementation is we won't get movement for free. Moving a model while its shown will now _always_ move it back to the placeholder position. You'll be forced to move the placeholder itself. This will need a separate issue to sync the model with the placeholder.

## Todo

Showing:
- [x] Move all the placeholders out of the workspace.
- [x] For each placeholder:
  - [x] Move it to a folder in ServerStorage.
  - [x] Clone in the prefab the placeholder represents.
  - [x] Create an ObjectValue mapping the placeholder to the newly cloned prefab.

Hiding:
- [x] Set the CFrame of each placeholder to the PrimaryPart CFrame of its associated model.
- [x] Clean up all the garbage from showing the prefabs.
- [x] If the ObjectValue's `Value` is missing, delete the placeholder.

- [x] Remove the addition of changing CanCollide on placeholder parts (db4cbd57a42ee2ac55eb7cfe48c41c9b275d8798). Since they no longer exist in the workspace there's no need to mess around with their collisions.
